# Generated by Django 3.0.5 on 2022-08-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0033_auto_20220824_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Coefficient'),
        ),
    ]
