# Generated by Django 3.0.5 on 2022-09-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0035_course_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='types',
            new_name='forme',
        ),
    ]
