# Generated by Django 3.0.5 on 2022-09-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0036_auto_20220906_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='forme',
            field=models.CharField(blank=True, choices=[('COURS', 'COURS'), ('MÉTHODE', 'MÉTHODE'), ('EXEMPLE', 'EXEMPLE'), ('VIDEO', 'VIDEO'), ('', 'PRESENTATION')], default='COURS', max_length=50, verbose_name='Type'),
        ),
    ]
