# Generated by Django 3.0.5 on 2022-11-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0040_auto_20221128_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexercise',
            name='etype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customexercises', to='qcm.Etype'),
        ),
    ]
