# Generated by Django 3.0.5 on 2023-02-07 08:03

from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_subject_is_active'),
        ('account', '0031_auto_20221014_1628'),
        ('qcm', '0041_customexercise_etype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supportchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.choice_directory_path, verbose_name='Image')),
                ('answer', models.TextField(blank=True, default='', null=True, verbose_name='Réponse écrite')),
                ('retroaction', models.TextField(blank=True, default='', null=True, verbose_name='Rétroaction')),
                ('audioanswer', models.FileField(blank=True, default='', null=True, upload_to=qcm.models.choice_directory_path, verbose_name='Audio')),
                ('imageanswerbis', models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.choice_directory_path, verbose_name='Image par paire')),
                ('answerbis', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse par paire')),
                ('audioanswerbis', models.FileField(blank=True, default='', null=True, upload_to=qcm.models.choice_directory_path, verbose_name='Audio')),
                ('is_correct', models.BooleanField(blank=True, default=0, verbose_name='Réponse correcte ?')),
                ('xmin', models.FloatField(blank=True, null=True, verbose_name='x min ')),
                ('xmax', models.FloatField(blank=True, null=True, verbose_name='x max ')),
                ('tick', models.FloatField(blank=True, null=True, verbose_name='Graduation principale')),
                ('subtick', models.FloatField(blank=True, null=True, verbose_name='Graduation')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='Précision')),
                ('is_written', models.BooleanField(blank=True, default=0, verbose_name='Mots à écrire ?')),
            ],
        ),
        migrations.CreateModel(
            name='Supportvariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='variable')),
                ('is_integer', models.BooleanField(default=1, verbose_name='Valeur entière ?')),
                ('is_notnull', models.BooleanField(default=1, verbose_name='Exclure 0 ?')),
                ('maximum', models.IntegerField(default=10)),
                ('minimum', models.IntegerField(default=0)),
                ('words', models.CharField(blank=True, max_length=255, verbose_name='Liste de valeurs')),
            ],
        ),
        migrations.AddField(
            model_name='supportfile',
            name='criterions',
            field=models.ManyToManyField(blank=True, related_name='supportfiles', to='qcm.Criterion'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_display_correction',
            field=models.BooleanField(default=0, verbose_name='Afficher le corrigé ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_mark',
            field=models.BooleanField(default=0, verbose_name='Notation ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_realtime',
            field=models.BooleanField(default=0, verbose_name='Temps réel ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_share',
            field=models.BooleanField(default=1, verbose_name='Mutualisé ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='mark',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Sur ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='nb_pseudo',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Nombre de pseudo situation'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='nb_subpseudo',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Nombre de pseudo proposition'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='qtype',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='annoncement',
            field=models.TextField(blank=True, default='', verbose_name='Consigne'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='supportfiles', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='correction',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Corrigé'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=550, verbose_name='Hauteur'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='imagefile',
            field=models.ImageField(blank=True, default='qtype_img/underlayer.png', upload_to=qcm.models.image_directory_path, verbose_name="Vignette d'accueil"),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='situation',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Pour valider le qcm', verbose_name='Nombre minimal de situations'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=750, verbose_name='Largeur'),
        ),
        migrations.CreateModel(
            name='SupportvariableImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to=qcm.models.vignette_directory_path, verbose_name='Image')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportvariables_img', to='qcm.Supportvariable')),
            ],
        ),
        migrations.AddField(
            model_name='supportvariable',
            name='supporfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportvariables', to='qcm.Supportfile'),
        ),
        migrations.CreateModel(
            name='Supportsubchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.subchoice_directory_path, verbose_name='Image')),
                ('answer', models.TextField(blank=True, default='', null=True, verbose_name='Réponse écrite')),
                ('retroaction', models.TextField(blank=True, default='', null=True, verbose_name='Rétroaction')),
                ('label', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Label')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
                ('supportchoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportsubchoices', to='qcm.Supportchoice')),
            ],
        ),
        migrations.AddField(
            model_name='supportchoice',
            name='supportfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportchoices', to='qcm.Supportfile'),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False)),
                ('done', models.BooleanField(blank=True, default=0)),
                ('relationships', models.ManyToManyField(editable=False, related_name='slots', to='qcm.Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='Prepeval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_stop', models.DateField()),
                ('mark', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('parcours', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prepevals', to='qcm.Parcours')),
                ('slots', models.ManyToManyField(editable=False, related_name='prepevals', to='qcm.Slot')),
                ('student', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prepevals', to='account.Student')),
                ('themes', models.ManyToManyField(related_name='prepevals', to='socle.Theme')),
            ],
        ),
    ]
