# Generated by Django 3.0.5 on 2023-02-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0042_auto_20230207_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepeval',
            old_name='date_stop',
            new_name='date',
        ),
    ]
