# Generated by Django 3.0.5 on 2023-02-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0043_auto_20230207_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepeval',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='prepeval',
            name='themes',
        ),
        migrations.AddField(
            model_name='slot',
            name='prepeval',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='qcm.Prepeval'),
        ),
        migrations.AlterField(
            model_name='prepeval',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=-1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='slot',
            name='relationships',
            field=models.ManyToManyField(blank=True, editable=False, related_name='slots', to='qcm.Relationship'),
        ),
    ]
