# Generated by Django 3.0.5 on 2023-02-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0044_auto_20230208_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='content',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
