# Generated by Django 3.0.5 on 2023-04-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0046_prepeval_o_parcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='is_ia',
            field=models.BooleanField(default=0, verbose_name='Intelligence Artificielle ?'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='is_testpos',
            field=models.BooleanField(default=0, editable=False, verbose_name='Test de positionnement ?'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Parcours cible'),
        ),
    ]
