# Generated by Django 3.0.5 on 2023-04-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0047_auto_20230429_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_calculator',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
