# Generated by Django 3.0.5 on 2023-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0048_relationship_is_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_paper',
            field=models.BooleanField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_paper',
            field=models.BooleanField(blank=True, default=0, verbose_name="Nécessite l'utilisation d'une feuille de papier"),
        ),
    ]
