# Generated by Django 3.0.5 on 2023-05-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0049_auto_20230504_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='is_paper',
            field=models.BooleanField(default=1, editable=False),
        ),
    ]
