# Generated by Django 3.0.5 on 2022-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_adhesion_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='is_lesson',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
