# Generated by Django 3.0.5 on 2022-10-14 14:46

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_teacher_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backtitle',
            field=models.ImageField(blank=True, default='', null=True, upload_to=account.models.background_directory_path, verbose_name='back title'),
        ),
    ]
