# Generated by Django 3.0.5 on 2022-10-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_background_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='title',
            new_name='is_title',
        ),
    ]
