# Generated by Django 3.0.5 on 2023-03-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0008_level_color'),
        ('account', '0031_auto_20221014_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_average', models.PositiveIntegerField(default=10)),
                ('target_average', models.PositiveIntegerField(default=10)),
                ('duration', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('job', models.CharField(max_length=50, verbose_name='Job')),
                ('hobbies', models.CharField(max_length=50, verbose_name='hobbies')),
                ('forces', models.ManyToManyField(blank=True, related_name='forces_descriptions', to='socle.Theme')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='account.Student')),
                ('weaknesses', models.ManyToManyField(blank=True, related_name='weakness_descriptions', to='socle.Theme')),
            ],
        ),
    ]
