# Generated by Django 3.0.5 on 2023-03-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='is_active',
            field=models.BooleanField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='parent',
            name='periodicity',
            field=models.PositiveIntegerField(default=7, verbose_name='Périodicité ? En nombre de jours'),
        ),
    ]
