# Generated by Django 3.0.5 on 2023-04-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20230331_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='orderID',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Numéro de paiement donné par Paypal'),
        ),
    ]
