# Generated by Django 3.0.5 on 2023-06-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20230418_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
