# Generated by Django 3.0.5 on 2022-09-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210904_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='gar',
        ),
        migrations.RemoveField(
            model_name='school',
            name='get_seconde_to_comp',
        ),
        migrations.RemoveField(
            model_name='school',
            name='rythme',
        ),
        migrations.AlterField(
            model_name='school',
            name='code_acad',
            field=models.CharField(default='999efe', max_length=255, verbose_name='Code UAI ou RNE'),
        ),
    ]
