# Generated by Django 3.0.5 on 2022-09-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20220915_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_managing',
            field=models.BooleanField(default=1, verbose_name='Admin unique ?'),
        ),
    ]
