# Generated by Django 3.0.5 on 2022-11-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_group_formule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='formule_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SANS Visio'), (2, 'AVEC Visio')], default=1),
        ),
    ]
