# Generated by Django 3.0.5 on 2023-03-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20221128_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='formule_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Autonomie'), (2, 'Suivi'), (3, "Prép'Exam"), (4, "Prep'Classe")], default=1),
        ),
    ]
