# Generated by Django 3.0.5 on 2023-04-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20230315_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_gar',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='is_hidden',
            field=models.BooleanField(default=0),
        ),
    ]
