# Generated by Django 3.0.5 on 2022-09-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='gar_abonnement_id',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='is_gar',
        ),
    ]
