# Generated by Django 3.0.5 on 2022-09-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_auto_20220915_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
