# Generated by Django 3.0.5 on 2022-09-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_remove_accounting_is_facturation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeyear',
            name='istest',
            field=models.BooleanField(default=0, verbose_name='Année active'),
        ),
    ]
