# Generated by Django 3.0.5 on 2023-06-19 19:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_school_is_managing'),
        ('account', '0034_auto_20230418_0917'),
        ('association', '0006_remove_accounting_is_facturation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10)),
                ('is_credit', models.BooleanField(default=0, verbose_name='is_credit ?')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet*')),
                ('chrono', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('mode', models.CharField(blank=True, choices=[('Période de test', "Période d'essai"), ('par carte de crédit', 'Carte de crédit'), ('par virement bancaire', 'Virement bancaire'), ('en espèces', 'Espèces'), ('par mandatement administratif', 'Mandatement administratif')], default='', max_length=255, verbose_name='Mode de paiement')),
                ('forme', models.CharField(blank=True, choices=[('FACTURE', 'FACTURE'), ('AVOIR', 'AVOIR')], default='FACTURE', max_length=255, verbose_name='Format')),
                ('beneficiaire', models.CharField(blank=True, max_length=255, verbose_name='En faveur de')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('town', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Contact')),
                ('observation', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Observation')),
                ('date_payment', models.DateTimeField(blank=True, null=True, verbose_name="Date d'effet")),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='school.Country', verbose_name='Pays')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='account.Parent', verbose_name='Etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Subinvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subinvoices', to='association.Invoice', verbose_name='Pays')),
            ],
        ),
    ]
