# Generated by Django 3.0.5 on 2023-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_invoice_subinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='mode',
        ),
    ]
