# Generated by Django 3.0.5 on 2023-06-21 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_remove_invoice_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_payment',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'effet"),
        ),
        migrations.AlterField(
            model_name='subinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subinvoices', to='association.Invoice', verbose_name='Facture'),
        ),
    ]
