# Generated by Django 3.0.5 on 2023-09-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_auto_20230621_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeyear',
            name='year',
            field=models.PositiveIntegerField(choices=[(2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026'), (2026, '2026-2027'), (2027, '2027-2028'), (2028, '2028-2029'), (2029, '2029-2030'), (2030, '2030-2031'), (2031, '2031-2032'), (2032, '2032-2033'), (2033, '2033-2034'), (2034, '2034-2035'), (2035, '2035-2036'), (2036, '2036-2037'), (2037, '2037-2038'), (2038, '2038-2039'), (2039, '2039-2040'), (2040, '2040-2041'), (2041, '2041-2042'), (2042, '2042-2043')], default=2021, verbose_name="Année de l'exercice"),
        ),
    ]
