# Generated by Django 3.0.5 on 2023-06-15 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socle', '0008_level_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidaybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Titre')),
                ('is_publish', models.BooleanField(default=1, verbose_name='Visible ?')),
                ('price', models.PositiveIntegerField(blank=True, default=5)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidaybooks', to='socle.Level', verbose_name='Niveau')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidaybooks', to='socle.Subject', verbose_name='Matière')),
            ],
        ),
    ]
