# Generated by Django 3.0.5 on 2023-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaybook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaybook',
            name='vignette',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
