# Generated by Django 3.0.5 on 2023-06-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20230429_1824'),
        ('holidaybook', '0003_holidaybook_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaybook',
            name='group',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidaybook', to='group.Group', verbose_name='Groupe'),
        ),
    ]
