# Generated by Django 3.0.5 on 2022-09-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_formuleprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formule',
            name='adhesion',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='nb_month',
        ),
    ]
