# Generated by Django 3.0.5 on 2023-06-21 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0035_auto_20230621_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturedys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrono', models.CharField(editable=False, max_length=50, verbose_name='Chrono')),
                ('date', models.DateField(auto_now_add=True)),
                ('orderID', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Numéro de paiement donné par CA')),
                ('adhesions', models.ManyToManyField(blank=True, editable=False, related_name='facturedys', to='account.Adhesion')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturedys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
