# Generated by Django 3.0.5 on 2022-10-01 07:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_subject_is_active'),
        ('tool', '0020_auto_20220927_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='question', to='socle.Skill'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Réponse écrite'),
        ),
    ]
