# Generated by Django 3.0.5 on 2022-10-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0022_answerpositionnement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answerpositionnement',
        ),
    ]
