# Generated by Django 3.0.5 on 2022-10-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0023_delete_answerpositionnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.PositiveIntegerField(blank=True, default=100, verbose_name='Point'),
        ),
    ]
