# Generated by Django 3.0.5 on 2023-02-07 08:03

from django.db import migrations, models
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0024_auto_20221002_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=255, verbose_name='Type')),
                ('imagefile', models.ImageField(blank=True, default='', upload_to=tool.models.qtype_directory_path, verbose_name='Image')),
                ('html', models.TextField(blank=True, default='', verbose_name='Html éventuel')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='url')),
                ('is_online', models.BooleanField(default=0, verbose_name='En ligne ?')),
                ('template', models.CharField(blank=True, default='', max_length=255, verbose_name='template de quizz')),
                ('ranking', models.PositiveIntegerField(default=0)),
                ('custom', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='template pour les exos')),
                ('is_sub', models.BooleanField(default=0)),
                ('is_alea', models.BooleanField(default=0)),
                ('extra', models.PositiveIntegerField(default=0)),
                ('is_pseudo', models.BooleanField(default=0)),
                ('is_insert', models.BooleanField(default=0)),
            ],
        ),
    ]
