# Generated by Django 3.0.5 on 2023-02-13 09:18

from django.db import migrations, models
import django.db.models.deletion
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0025_qtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answerbis',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse par paire'),
        ),
        migrations.AddField(
            model_name='choice',
            name='audioanswer',
            field=models.FileField(blank=True, default='', null=True, upload_to=tool.models.choice_directory_path, verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='choice',
            name='audioanswerbis',
            field=models.FileField(blank=True, default='', null=True, upload_to=tool.models.choice_directory_path, verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='choice',
            name='imageanswerbis',
            field=models.ImageField(blank=True, default='', null=True, upload_to=tool.models.choice_directory_path, verbose_name='Image par paire'),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_written',
            field=models.BooleanField(blank=True, default=0, verbose_name='Mots à écrire ?'),
        ),
        migrations.AddField(
            model_name='choice',
            name='precision',
            field=models.FloatField(blank=True, null=True, verbose_name='Précision'),
        ),
        migrations.AddField(
            model_name='choice',
            name='subtick',
            field=models.FloatField(blank=True, null=True, verbose_name='Graduation'),
        ),
        migrations.AddField(
            model_name='choice',
            name='tick',
            field=models.FloatField(blank=True, null=True, verbose_name='Graduation principale'),
        ),
        migrations.AddField(
            model_name='choice',
            name='xmax',
            field=models.FloatField(blank=True, null=True, verbose_name='x max '),
        ),
        migrations.AddField(
            model_name='choice',
            name='xmin',
            field=models.FloatField(blank=True, null=True, verbose_name='x min '),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Réponse écrite'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(blank=True, default=0, verbose_name='Réponse correcte ?'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='retroaction',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Rétroaction'),
        ),
        migrations.CreateModel(
            name='Subchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=tool.models.choice_directory_path, verbose_name='Image')),
                ('answer', models.TextField(blank=True, default='', null=True, verbose_name='Réponse écrite')),
                ('retroaction', models.TextField(blank=True, default='', null=True, verbose_name='Rétroaction')),
                ('label', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Label')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
                ('supportchoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchoices', to='tool.Choice')),
            ],
        ),
    ]
