# Generated by Django 3.0.5 on 2023-02-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0026_auto_20230213_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True, default='', verbose_name='Réponse écrite'),
        ),
    ]
