# Generated by Django 3.0.5 on 2023-02-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0027_auto_20230213_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subchoice',
            old_name='supportchoice',
            new_name='choice',
        ),
    ]
