# Generated by Django 3.0.5 on 2023-02-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0029_auto_20230225_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionnement',
            name='nb_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
