# Generated by Django 3.0.5 on 2023-11-19 07:27

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0030_positionnement_nb_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicpositionnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code')),
                ('last_name', models.CharField(default='Test de positionnement', max_length=255)),
                ('first_name', models.CharField(default='Test de positionnement', max_length=255)),
                ('email', models.CharField(default='Test de positionnement', max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('positionement', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='positionnements', to='tool.Positionnement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
