# Generated by Django 3.0.5 on 2022-08-29 10:47
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnexionEleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlJoinEleve', models.CharField(blank=True, max_length=250, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('notification', models.BooleanField(blank=True, default=False, verbose_name='Notification?')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('display', models.BooleanField(default=0, verbose_name='Publication')),
                ('color', models.CharField(default='#00819F', max_length=50, verbose_name='color')),
                ('urlCreate', models.CharField(blank=True, max_length=1000, null=True, verbose_name='urlCreate')),
                ('urlJoinProf', models.CharField(blank=True, max_length=250, null=True, verbose_name='urlJoinProg')),
                ('urlIsMeetingRunning', models.CharField(blank=True, max_length=250, null=True, verbose_name='urlRunning?')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, default='', related_name='these_events', related_query_name='these_events', through='lesson.ConnexionEleve', to=settings.AUTH_USER_MODEL, verbose_name='Partagée avec')),
            ],
            options={
                'verbose_name': 'event',
                'ordering': ['start', 'end'],
            },
        ),
        migrations.AddField(
            model_name='connexioneleve',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.Event'),
        ),
        migrations.AddField(
            model_name='connexioneleve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
