# Generated by Django 3.0.5 on 2022-09-12 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lesson.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10)),
                ('effective', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10)),
                ('observation', models.TextField(blank=True, default='', null=True, verbose_name='Observation')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('facture', models.FileField(blank=True, default='', upload_to=lesson.models.credit_directory_path, verbose_name='Facture')),
                ('chrono', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
