# Generated by Django 3.0.5 on 2022-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_validate',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Validation?'),
        ),
    ]
