# Generated by Django 3.0.5 on 2022-09-01 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='start',
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
