# Generated by Django 3.0.5 on 2022-09-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20220915_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Réalisée ?'),
        ),
    ]
