# Generated by Django 3.0.5 on 2022-09-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_auto_20220901_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='date',
            new_name='datetime',
        ),
    ]
