# Generated by Django 3.0.5 on 2022-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_auto_20220917_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_validate',
        ),
        migrations.AddField(
            model_name='connexioneleve',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Réalisée ?'),
        ),
        migrations.AddField(
            model_name='connexioneleve',
            name='is_validate',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Validation?'),
        ),
    ]
