# Generated by Django 3.0.5 on 2022-09-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_auto_20220901_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_oupied',
            field=models.BooleanField(blank=True, default=False, verbose_name='Notification?'),
        ),
    ]
