# Generated by Django 3.0.5 on 2022-09-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_slot_is_oupied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='is_oupied',
        ),
    ]
