# Generated by Django 3.0.5 on 2022-09-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_auto_20220920_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='is_occupied',
            field=models.PositiveIntegerField(blank=True, default=False, verbose_name='Blocage du slot ?'),
        ),
    ]
