# Generated by Django 3.0.5 on 2022-09-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='display',
        ),
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=0, verbose_name='Privée ?'),
        ),
    ]
