# Generated by Django 3.0.5 on 2023-03-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_subject_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='color',
            field=models.CharField(blank=True, default='#46119c', max_length=255, null=True, verbose_name='Couleur*'),
        ),
    ]
