# Generated by Django 3.0.5 on 2023-04-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0018_auto_20230418_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotex',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='exotex',
            name='is_annals',
            field=models.BooleanField(default=0, verbose_name='Annale ?'),
        ),
    ]
