# Generated by Django 3.0.5 on 2023-06-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0019_auto_20230430_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotex',
            name='is_annal',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Annale ?'),
        ),
    ]
